//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalliPoshApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public int Id { get; set; }
        public string Genre1 { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> NumberInStock { get; set; }
    }
}
